### ISSUE TITLE
有成功的吗？cookie格式怎么填？

### ISSUE THREAD

**Issue by le45tx1m** [pigeoner/bilibili_dynamic_thumps_up#1]
B站都升级几个版本了，cookie格式也不断地在变化，不知道怎么填啊

**Comment by pigeoner** [comment]
> B站都升级几个版本了，cookie格式也不断地在变化，不知道怎么填啊

参考[B站获取Cookie](https://blog.csdn.net/weixin_53891182/article/details/125846559)一文中的方法，使用该格式的cookie即可

**Comment by le45tx1m** [comment]
谢谢，成功了，之前一直卡在收集点赞动态那里，原来是数量太多，我还以为是失败了呢。

**Comment by pigeoner** [comment]
> 谢谢，成功了，之前一直卡在收集点赞动态那里，原来是数量太多，我还以为是失败了呢。

感谢提醒，动态获取阶段确实没有任何输出信息容易使人误认为程序卡住了，我会在最新的一版中加入提示信息
